### PR TITLE
% in timestring param causes cron job to fail.

### PR DESCRIPTION
**Pull request by SteveDevOps**
When crontab sees percent sign it expects STDIN, and job command essentially gets truncated when running under cron. Validated this in production environment, made fix and tested. Before fix, cron log indicated command truncation.

### CODE REVIEW

**Comment by fvanboven** [comment]
Had exactly the same problem (and fix) as this.

If this could be merged, that would be awesome. We fixed this is wrapper code for now, an "official" fix would be nice.

**Comment by SteveDevOps** [comment]
*sigh* I think the problem is this issue isn't *in your face* (no upfront error messages) unless you happen to be watching your indices not being managed right and your cron log entries. Otherwise more folks would be chiming in. And I don't like being off the official release either.. *bonkbonk* MERGE plz??

**Comment by jlambert121** [comment]
Thanks!  Sorry for the delay on this

**Comment by jlambert121** [comment]
2.1.1 released

**Pull request merged**
